version: "3.9"

services:
  docker-api:
    image: marcpartensky/docker-api
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
     - "8080:80"
